# Generated by Django 3.1.7 on 2022-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
