# Generated by Django 3.1.7 on 2022-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AYY_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dateofcreation', models.DateTimeField(max_length=255)),
            ],
        ),
    ]
