# Generated by Django 4.0.4 on 2022-05-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AYY_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='younes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dateofcreation', models.DateTimeField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
