# Generated by Django 4.0.4 on 2022-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AYY_app', '0003_younes_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='younes',
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofcreation',
            field=models.DateTimeField(auto_now_add=True, max_length=255),
        ),
    ]
